We need more version pins so the buildout succeeds for 4.2-5.0.
In Plone 5.0 you do get a ComponentLookupError in one test.
We are already allowing test failures on 5.0 in Travis.
But now the buildout at least finishes, and five of the six tests pass.

Error in test test_controlpanel_has_view (plone.app.ldap.tests.test_controlpanel.ControlPanelTestCase)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/maurits/clients/vmm/hoofdsite-9151/checkouts/plone.app.ldap/plone/app/ldap/tests/test_controlpanel.py", line 22, in test_controlpanel_has_view
    self.assertTrue(view())
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 868, in __call__
    self.update()
  File "/Users/maurits/shared-eggs/cp27m/five.formlib-1.0.4-py2.7.egg/five/formlib/formbase.py", line 50, in update
    super(FiveFormlibMixin, self).update()
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 831, in update
    self.setUpWidgets()
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 906, in setUpWidgets
    adapters=self.adapters, ignore_request=ignore_request
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 407, in setUpEditWidgets
    widget = _createWidget(form_field, field, request, iface)
  File "/Users/maurits/shared-eggs/cp27m/zope.formlib-4.3.0-py2.7.egg/zope/formlib/form.py", line 337, in _createWidget
    return component.getMultiAdapter((field, request), iface)
  File "/Users/maurits/shared-eggs/cp27m/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 109, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
ComponentLookupError: ((<zope.schema._field.Choice object at 0x10f669f10>, <HTTPRequest, URL=http://nohost>), <InterfaceClass zope.formlib.interfaces.IInputWidget>, u'')