fix setuptools (not 'setuptool')
Was broken in f0bff65, leading to this error:

Develop distribution: plone.app.ldap 1.3.2.dev0
uses namespace packages but the distribution does not require setuptools.
Couldn't find index page for 'setuptool' (maybe misspelled?)
Getting distribution for 'setuptool'.
Couldn't find index page for 'setuptool' (maybe misspelled?)
While:
  Updating client1.
  Getting distribution for 'setuptool'.
Error: Couldn't find a distribution for 'setuptool'.